version: '3'
services:

  todotests:
    depends_on:
      - todofront
    build: ./todo-app/tests
    restart: always
    environment:
      FRONT_HOST: todofront  

  todofront:
    depends_on:
      - todoback
    build: ./todo-app/front-end
    restart: always
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_HOST: todoback

  todoback:
    build: ./todo-app/back-end
    restart: always
    ports:
      - 3001:3001
      